### ISSUE TITLE
Do not change zoom when "Send to back" is applied

### ISSUE THREAD

**Issue by AndrewMWebster** [Zachatoo/obsidian-canvas-send-to-back#3]
I've tried to use this feature to have a large card "group" other cards on the canvas by sending it behind them.  
But each time I apply it, the view zooms all the way back out, and I have to zoom back in to where I was working.  This is definitely not a desirable behavior!  I'm trying to organize a very large canvas, and having to lose and re-find my place in the very process of organizing it, well, that doesn't work!
Any chance you can update the plug-in so either it simply doesn't do that, or that it's a toggleable option.
Thanks!

**Comment by Zachatoo** [comment]
Fixed in 0.0.4, thanks for the report!
